name: github pages

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: ./app

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup for using PlantUML
        run: sudo apt-get update && sudo apt-get install -y build-essential openjdk-11-jre graphviz plantuml

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.4"

      - name: install mdbook plantuml
        run: cargo install mdbook-plantuml --no-default-features

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/book
